### ISSUE TITLE
pipeline memory leak

### ISSUE THREAD

**Issue by seiyap70** [facebook/wangle#106]
Could please some explains where and when pipeline objects be freed? Because I never go to pipeline  destruct function.

**Comment by snarkmaster** [comment]
Thanks for writing! It sounds like you are asking something along the lines of "how do C++ destruction semantics work?" -- but since this is a big topic that is covered in the language specification, in textbooks, and in many tutorials, it does not seem useful to repeat all that information here. 

If you want a more specific answer, I think anybody would struggle to answer your question without a code sample that shows what you are trying to do. 

Please do re-open the issue if you are able to give enough context.
