### ISSUE TITLE
[Fedora] undefined reference to ssl

### ISSUE THREAD

**Issue by gelidus** [facebook/wangle#29]
I recently compiled the Wangle library without libatomic (as it errors on Fedora 23). I just tried to build server that is very close to echo example in the implementation. When trying to build, this is what happens:

```
usr/bin/ld: /usr/local/lib/libwangle.a(SSLSessionCacheManager.cpp.o): undefined reference to symbol 'SSL_CTX_get_ex_new_index@@libssl.so.10'
/usr/lib64/libssl.so.10: error adding symbols: DSO missing from command line
```

libssl can be found in the given directories. Is there a way to disable SSLSessionCacheManager? Am I missing any dependencies?

What I did:
- compiled folly, installed
- removed libatomic from wangle, compiled, installed
- tried to compile implementation that has nothing more than echo example

**Comment by anirudhvr** [comment]
Sorry for the delay. Can you check your SSL version (usually just 'openssl version')? SSL_CTX_get_ex_new_index has been around at least since OpenSSL 1.0.1.

The 'DSO missing from command line' also may indicate a linking order in your build command. Can you confirm that the build command includes -L <path to libssl.so> -lssl at the end (after the .o files).

**Comment by gelidus** [comment]
OpenSSL version: OpenSSL 1.0.2f-fips  28 Jan 2016

I will try the ssl link tomorrow, but I was using CMake tool and added the *openssl*. Not sure if the pure *ssl* was present.

**Comment by anirudhvr** [comment]
OpenSSL is just two libraries, libcrypto and libssl. It'd help if you can post the link command invocation that caused the failure (should be in some cmake log),

**Comment by gelidus** [comment]
Will look into this during the summer when I have enough time, thanks for the support :)

Closing for now.
