### ISSUE TITLE
Building error at Acceptor.cpp

### ISSUE THREAD

**Issue by chengzhanzhan** [facebook/wangle#48]
A error occurs as follows:

$ make
[ 17%] Built target gmock
[ 17%] Building CXX object CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o

/home/zzcheng/software/wangle/wangle/acceptor/Acceptor.cpp: In member function 'void wangle::Acceptor::connectionReady(folly::AsyncTransportWrapper::UniquePtr, const folly::SocketAddress&, const string&, SecureTransportType, wangle::TransportInfo&)':
/home/zzcheng/software/wangle/wangle/acceptor/Acceptor.cpp:256:28: error: 'class folly::AsyncTransportWrapper' has no member named 'getUnderlyingTransport'
   auto asyncSocket = sock->getUnderlyingTransport<AsyncSocket>();
                            ^
/home/zzcheng/software/wangle/wangle/acceptor/Acceptor.cpp:256:62: error: expected primary-expression before '>' token
   auto asyncSocket = sock->getUnderlyingTransport<AsyncSocket>();
                                                              ^
/home/zzcheng/software/wangle/wangle/acceptor/Acceptor.cpp:256:64: error: expected primary-expression before ')' token
   auto asyncSocket = sock->getUnderlyingTransport<AsyncSocket>();
                                                                ^
make[2]: *** [CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o] Error 1
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
make: *** [all] Error 2

thanks.

**Comment by chengzhanzhan** [comment]
When I reinstall the folly, the problem is solved.

**Comment by snarkmaster** [comment]
@chengzhanzhan, thanks for your report! 

Since both wangle and folly evolve quickly, one can currently run into situations where the two "master" versions of the repos are divergent. 

We wrote some code that should make finding matching checkouts of the repositories easier in the future. It may take a few weeks before we manage to release it, though.

I'll close the issue, since I'm not sure if there is anything else to do at this point.
